### ISSUE TITLE
Move to official organization?

### ISSUE THREAD

**Issue by iandunn** [WordPress/meeting-calendar#117]
What was the reason to create this repo under `/Automattic` instead of `/WordPress` ? Does that reason still apply?

If it was built for w.org and is running there, it seems like it should be "owned" by the community rather than A8C.

**Comment by ryelle** [comment]
I think it was (or was planned to be) released to the plugin directory under Automattic, that might be why?

**Comment by dd32** [comment]
I've gone ahead and migrated it from the Automattic to WordPress github organisation. The package files still need to be updated with the new location.
