### ISSUE TITLE
Synchronization with the baikal server

### ISSUE THREAD

**Issue by ZicPL** [WordPress/meeting-calendar#156]
Hello, are there any plans to add support for the baikal calendar server?
If it is planned, that would be great!
By "support" I mean adding events and synchronizing them with the calendar feed.

Kind regards

**Comment by dd32** [comment]
No, no planned support.

This plugin is intentionally developed for use on make.wordpress.org and not designed for wider usage.  

Calendar feeds in ical (which has become a standard of sorts) is offered for ingestion into other platforms / calendar apps.

**Comment by ZicPL** [comment]
Thank you for Your quick and informative response.

I sought a solution for basic event management, specifically adding and removing events without requiring a full calendar feature. Unfortunately, my research indicates that this functionality is primarily available as a premium service.

I wish you continued success in your projects. Please do not hesitate to contact me if necessary.
