### ISSUE TITLE
Redesign frontend

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/meeting-calendar#158]
We introduced new styles for the calendar in the Learn WordPress redesign but these were kept as local overrides. We now need to update the Make WordPress calendar as well. There are designs for both, and we need to settle on styles and layout that cater to both:

### Designs

| Make | Learn - Calendar | Learn - List |
|--------|--------|-|
| ![Image](https://github.com/user-attachments/assets/c118d5e1-81a0-4776-be4e-cf72181fe66c) | ![Image](https://github.com/user-attachments/assets/4c690cdd-a6ca-44a4-88de-163a64bcffe7) | ![Image](https://github.com/user-attachments/assets/d08a75ce-996b-4825-9cab-a7d2bd495e9f) |

**Comment by vk17-starlord** [comment]
@adamwoodnz  @stephdau  @rawrly  @nb  
i would like to be part of this redesign sprint ? how can I exactly contribute to this can you just tell me In short ?

**Comment by adamwoodnz** [comment]
Hi @vk17-starlord, good to know! Do you mean this Meeting Calendar update or the larger wordpress.org redesign?

This Meeting Calendar update is a fairly small effort so I won't need assistance sorry. If you're interested in the wider redesign project I'd suggest looking at the issues on the [project board](https://github.com/orgs/WordPress/projects/40/views/1) to see if there's something that interests you.
